# Generated by Django 3.1.4 on 2020-12-10 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchemaDataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.BooleanField(null=True)),
                ('email', models.BooleanField(null=True)),
                ('phone_number', models.BooleanField(null=True)),
                ('company_name', models.BooleanField(null=True)),
                ('text', models.BooleanField(null=True)),
                ('integer', models.BooleanField(null=True)),
                ('date', models.BooleanField(null=True)),
                ('address', models.BooleanField(null=True)),
                ('row_num', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FakeDataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fake_data.schemadatamodel')),
            ],
        ),
    ]
