# Generated by Django 3.1.4 on 2020-12-20 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchemaDataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('modified', models.DateField(auto_now=True)),
                ('name', models.BooleanField(default=True)),
                ('email', models.BooleanField(default=True)),
                ('phone_number', models.BooleanField(default=True)),
                ('company', models.BooleanField(default=True)),
                ('text', models.BooleanField(default=True)),
                ('random_int', models.BooleanField(default=True)),
                ('date', models.BooleanField(default=True)),
                ('address', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FakeDataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_num', models.PositiveIntegerField(default=True)),
                ('url', models.URLField(blank=True, editable=False, null=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fake_data.schemadatamodel')),
            ],
        ),
    ]
