# Generated by Django 3.1.4 on 2020-12-13 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fake_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schemadatamodel',
            old_name='company_name',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='schemadatamodel',
            old_name='full_name',
            new_name='name',
        ),
    ]
