# Generated by Django 3.1.4 on 2020-12-13 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fake_data', '0002_auto_20201213_1852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schemadatamodel',
            old_name='integer',
            new_name='random_int',
        ),
    ]
