# Generated by Django 3.1.4 on 2020-12-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fake_data', '0005_auto_20201214_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fakedatamodel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
    ]
