# Generated by Django 3.1.4 on 2020-12-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fake_data', '0006_auto_20201214_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fakedatamodel',
            name='file',
        ),
        migrations.AddField(
            model_name='fakedatamodel',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
